# Prometheus Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.defaults.source.repoURL }}
    targetRevision: {{ .Values.defaults.source.targetRevision }}
    path: ha/k8s/addons/monitoring/prometheus
  destination:
    server: {{ .Values.defaults.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# Grafana Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.defaults.source.repoURL }}
    targetRevision: {{ .Values.defaults.source.targetRevision }}
    path: ha/k8s/addons/monitoring/grafana
  destination:
    server: {{ .Values.defaults.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# NFS Exporter Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.defaults.source.repoURL }}
    targetRevision: {{ .Values.defaults.source.targetRevision }}
    path: ha/k8s/addons/monitoring/nfs-exporter
  destination:
    server: {{ .Values.defaults.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# Monitoring Namespace Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-namespace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.defaults.source.repoURL }}
    targetRevision: {{ .Values.defaults.source.targetRevision }}
    path: ha/k8s/addons/monitoring
    directory:
      include: "namespace.yaml"
  destination:
    server: {{ .Values.defaults.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
