defaults:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/hashfoundry/infra.git
    targetRevision: HEAD

apps: []
addons:
  - name: nginx-ingress
    namespace: ingress-nginx
    project: default
    source:
      path: k8s/addons/nginx-ingress
      helm:
        valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
