defaults:
  env: prod
  source:
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values.prod.yaml

apps:
  - name: hashfoundry-react
    namespace: hashfoundry-react-prod
    autosync: true

addons:
  - name: argo-cd-apps
    namespace: argocd
    autosync: true
