defaults:
  env: dev
  source:
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values.dev.yaml

apps:
  - name: hashfoundry-react
    namespace: hashfoundry-react-dev
    autosync: true

addons:
  - name: argo-cd-apps
    namespace: argocd
    autosync: true
