defaults:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/hashfoundry/infra.git
    targetRevision: HEAD

apps: []
addons: []
