defaults:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/hashfoundry/infra.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  env: dev

apps:
  - name: hashfoundry-react
    namespace: hashfoundry-react-dev
    autosync: true

addons:
  - name: nginx-ingress
    namespace: ingress-nginx
    project: default
    source:
      path: k8s/addons/nginx-ingress
      helm:
        valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
    autosync: true
  - name: argocd-ingress
    namespace: argocd
    project: default
    source:
      path: k8s/addons/argocd-ingress
      helm:
        valueFiles:
          - values.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    autosync: true
  - name: argo-cd-apps
    namespace: argocd
    autosync: true
