apiVersion: v2
name: istio
description: A Helm chart for Istio Service Mesh
type: application
version: 0.1.0
appVersion: "1.19.0"

dependencies:
  - name: base
    version: 1.19.0
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.19.0
    repository: https://istio-release.storage.googleapis.com/charts
