apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "substrate-blockchain.fullname" . }}-config
  labels:
    {{- include "substrate-blockchain.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  # Chain configuration
  chain-type: {{ .Values.global.network.chainType | quote }}
  protocol-id: {{ .Values.global.network.protocolId | quote }}
  token-symbol: {{ .Values.global.network.tokenSymbol | quote }}
  token-decimals: {{ .Values.global.network.tokenDecimals | quote }}
  
  # Node configuration
  node-key-strategy: {{ .Values.nodeKeyStrategy | quote }}
  
  # Runtime configuration
  rust-log: "info"
  rust-backtrace: "1"
