apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "substrate-blockchain.serviceAccountName" . }}
  labels:
    {{- include "substrate-blockchain.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
