apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-model-storage
  namespace: ml-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
