apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
  namespace: ml-models
  annotations:
    serving.kserve.io/s3-endpoint: "https://nyc3.digitaloceanspaces.com"
    serving.kserve.io/s3-region: "nyc3"
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-verifyssl: "1"
    serving.kserve.io/s3-configmap: "storage-config-cm"
secrets:
  - name: storage-config
