# Default values for argocd-ingress
nameOverride: ""
fullnameOverride: "argocd-server-ingress"

# Target namespace for ArgoCD
namespace: argocd

# Ingress configuration
ingress:
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # ArgoCD server runs in insecure mode behind Ingress
  hosts:
    - host: argocd.hashfoundry.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port: 80
  tls: []
    # - secretName: argocd-tls
    #   hosts:
    #     - argocd.hashfoundry.local
