apiVersion: v2
name: nginx-ingress
description: A Helm chart for NGINX Ingress Controller
type: application
version: 1.0.0

dependencies:
  - name: ingress-nginx
    version: 4.8.3
    repository: https://kubernetes.github.io/ingress-nginx
