ingress-nginx:
  controller:
    # Use DigitalOcean LoadBalancer for the ingress controller
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-algorithm: round_robin
        service.beta.kubernetes.io/do-loadbalancer-protocol: http
        service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "false"
        service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: none
        service.beta.kubernetes.io/do-loadbalancer-type: REGIONAL_NETWORK
        service.beta.kubernetes.io/do-loadbalancer-name: "hashfoundry-ingress-lb"
    
    # Enable metrics for monitoring
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
    
    # Resource limits
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # Replica count for HA
    replicaCount: 3
    
    # Node tolerations
    tolerations:
      - key: node-restriction.kubernetes.io/management
        operator: Exists
    
    # Anti-affinity for HA distribution
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: ingress-nginx
                app.kubernetes.io/component: controller
            topologyKey: kubernetes.io/hostname
    
    # Configuration for better performance
    config:
      # Enable real IP forwarding
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      use-proxy-protocol: "false"
      
      # SSL configuration
      ssl-redirect: "true"
      force-ssl-redirect: "true"
      
      # Performance tuning
      worker-processes: "1"
      max-worker-connections: "1024"
      
      # Security headers
      add-headers: "ingress-nginx/custom-headers"
    
    # Admission webhooks
    admissionWebhooks:
      enabled: true
      failurePolicy: Fail
      
  # Default backend for HA
  defaultBackend:
    enabled: true
    replicaCount: 2
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: ingress-nginx
                app.kubernetes.io/component: default-backend
            topologyKey: kubernetes.io/hostname
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
