apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-controller-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-default-backend-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/component: default-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: default-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
