apiVersion: v1
kind: Namespace
metadata:
  name: hashfoundry-react-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashfoundry-react
  namespace: hashfoundry-react-dev
  labels:
    app: hashfoundry-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashfoundry-react
  template:
    metadata:
      labels:
        app: hashfoundry-react
    spec:
      containers:
      - name: hashfoundry-react
        image: docker.io/alexhashfoundry/hashfoundry-react:a2a2679b096d59206a2c24e53d2c815a25cde7c8
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hashfoundry-react
  namespace: hashfoundry-react-dev
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-algorithm: round_robin
    service.beta.kubernetes.io/do-loadbalancer-protocol: http
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "false"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: none
    service.beta.kubernetes.io/do-loadbalancer-type: REGIONAL_NETWORK
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hashfoundry-react
