nginx:
  # Production environment specific configuration
  replicaCount: 3
  
  # Image configuration
  image:
    registry: docker.io
    repository: alexhashfoundry/hashfoundry-react
    tag: a2a2679b096d59206a2c24e53d2c815a25cde7c8
    pullPolicy: IfNotPresent
  
  # Security context for the container to fix permission issues
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  
  # Pod security context
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  
  # Service configuration for production
  service:
    type: ClusterIP
    port: 80
  
  # Configure Nginx to serve the React application
  serverBlock: |-
    server {
      listen 0.0.0.0:8080;
      server_name localhost;
      
      location /status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all;
      }
      
      location / {
        root /app;
        index index.html;
        try_files $uri $uri/ /index.html;
      }
    }
  
  # Resource limits and requests for production
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
      
  # Autoscaling configuration for production
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    
  # Ingress configuration for production
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: app.hashfoundry.local
        paths:
          - path: /
            pathType: Prefix
            
  # Monitoring configuration for production
  metrics:
    enabled: true
