nginx:
  # Development environment specific configuration
  replicaCount: 1
  
  # Image configuration
  image:
    registry: docker.io
    repository: alexhashfoundry/hashfoundry-react
    tag: a2a2679b096d59206a2c24e53d2c815a25cde7c8
    pullPolicy: IfNotPresent
    
  # Security context for the container to fix permission issues
  containerSecurityContext:
    enabled: false
  
  # Pod security context
  podSecurityContext:
    enabled: false
    
  # Init containers to set up permissions
  extraInitContainers:
    - name: init-nginx-permissions
      image: busybox
      command: ['sh', '-c', 'mkdir -p /bitnami/nginx/tmp && chmod -R 777 /bitnami/nginx']
      volumeMounts:
        - name: nginx-data
          mountPath: /bitnami/nginx
          
  # Extra volumes for Nginx
  extraVolumes:
    - name: nginx-data
      emptyDir: {}
      
  # Extra volume mounts for Nginx
  extraVolumeMounts:
    - name: nginx-data
      mountPath: /bitnami/nginx
  
  # Service configuration for dev
  service:
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-algorithm: round_robin
      service.beta.kubernetes.io/do-loadbalancer-protocol: http
      service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "false"
      service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: none
      service.beta.kubernetes.io/do-loadbalancer-type: REGIONAL_NETWORK
  
  # Configure Nginx to serve the React application
  containerPorts:
    http: 80
    
  serverBlock: |-
    server {
      listen 0.0.0.0:80;
      server_name localhost;
      
      location /status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all;
      }
      
      location / {
        root /app;
        index index.html;
        try_files $uri $uri/ /index.html;
      }
    }
  
  # Resource limits and requests for dev
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
      
  # Autoscaling configuration for dev
  autoscaling:
    enabled: false
    
  # Ingress configuration for dev
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: hashfoundry-react-dev.example.com
        paths:
          - path: /
            pathType: Prefix
            
  # Monitoring configuration for dev
  metrics:
    enabled: false
    
  # Liveness and readiness probes
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
    httpGet:
      path: /status
      port: 80
    
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
    httpGet:
      path: /status
      port: 80
