argo-cd:
  crds:
    keep: false

  global:
    tolerations:
      - key: node-restriction.kubernetes.io/management
        operator: Exists

  redis-ha:
    enabled: false

  redis:
    enabled: true
    tolerations:
      - key: node-restriction.kubernetes.io/management
        operator: Exists

  controller:
    replicas: 1

  server:
    replicas: 2
    service:
      type: ClusterIP
    ingress:
      enabled: false
    # Run in insecure mode since we use Ingress for TLS termination
    extraArgs:
      - --insecure

  repoServer:
    replicas: 2

  applicationSet:
    replicas: 2

  dex:
    enabled: true

  notifications:
    enabled: true

  # Configure parameters
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
