argo-cd:
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true

  server:
    service:
      type: ClusterIP
    ingress:
      enabled: false
    # Run in insecure mode since we use Ingress for TLS termination
    extraArgs:
      - --insecure
