argo-cd:
  crds:
    keep: false

  global:
    tolerations:
      - key: node-restriction.kubernetes.io/management
        operator: Exists

  redis-ha:
    enabled: true
    tolerations:
      - key: node-restriction.kubernetes.io/management
        operator: Exists
    replicas: 1
    servers: 1
    haproxy:
      replicas: 1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: redis-ha-haproxy
                  release: argocd
              topologyKey: kubernetes.io/hostname
    redis:
      config:
        save: "900 1"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: redis-ha
                  release: argocd
              topologyKey: kubernetes.io/hostname

  controller:
    replicas: 1

  server:
    replicas: 2

  repoServer:
    replicas: 2

  applicationSet:
    replicas: 2

  dex:
    enabled: true

  notifications:
    enabled: true
