apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.nfsProvisioner.storageClass.name }}
  labels:
    {{- include "nfs-provisioner.provisionerLabels" . | nindent 4 }}
  {{- if .Values.nfsProvisioner.storageClass.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ include "nfs-provisioner.fullname" . }}/nfs
parameters:
  archiveOnDelete: "false"
reclaimPolicy: {{ .Values.nfsProvisioner.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.nfsProvisioner.storageClass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.nfsProvisioner.storageClass.allowVolumeExpansion }}
