metrics-server:
  args:
    - --cert-dir=/tmp
    - --secure-port=10250
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
    # Для dev кластеров может потребоваться:
    - --kubelet-insecure-tls
  
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
      
  # High availability configuration
  replicas: 2
  
  # Pod disruption budget for HA
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    
  # Anti-affinity for HA distribution
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              k8s-app: metrics-server
          topologyKey: kubernetes.io/hostname
