apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockchain.fullname" . }}-chainspec
  namespace: {{ include "blockchain.namespace" . }}
  labels:
    {{- include "blockchain.labels" . | nindent 4 }}
data:
  genesis.json: |
    {
      "name": "{{ .Values.blockchain.chainName }}",
      "id": "{{ .Values.blockchain.chainId }}",
      "chainType": "Local",
      "bootNodes": [],
      "telemetryEndpoints": null,
      "protocolId": "hf",
      "properties": {
        "tokenSymbol": "{{ .Values.blockchain.tokenSymbol }}",
        "tokenDecimals": {{ .Values.blockchain.tokenDecimals }},
        "ss58Format": {{ .Values.blockchain.ss58Format }}
      },
      "codeSubstitutes": {},
      "genesis": {
        "runtime": {
          "system": {
            "code": "0x"
          },
          "balances": {
            "balances": [
              [
                "{{ .Values.validatorAlice.account.address }}",
                {{ .Values.validatorAlice.account.initialBalance }}
              ],
              [
                "{{ .Values.validatorBob.account.address }}",
                {{ .Values.validatorBob.account.initialBalance }}
              ]
            ]
          },
          "aura": {
            "authorities": [
              "{{ .Values.validatorAlice.account.address }}",
              "{{ .Values.validatorBob.account.address }}"
            ]
          },
          "grandpa": {
            "authorities": [
              [
                "{{ .Values.validatorAlice.account.address }}",
                1
              ],
              [
                "{{ .Values.validatorBob.account.address }}",
                1
              ]
            ]
          },
          "sudo": {
            "key": "{{ .Values.validatorAlice.account.address }}"
          },
          "transactionPayment": {
            "multiplier": "1000000000000000000"
          }
        }
      }
    }
