apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: 0.1.0
appVersion: "v1.13.0"

dependencies:
  - name: cert-manager
    version: v1.13.0
    repository: https://charts.jetstack.io
