apiVersion: v1
kind: Namespace
metadata:
  name: blockchain
  labels:
    name: blockchain
    app.kubernetes.io/name: blockchain
    app.kubernetes.io/part-of: hashfoundry
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blockchain-serviceaccount
  namespace: blockchain
  labels:
    app.kubernetes.io/name: blockchain
    app.kubernetes.io/part-of: hashfoundry
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: blockchain-role
  namespace: blockchain
  labels:
    app.kubernetes.io/name: blockchain
    app.kubernetes.io/part-of: hashfoundry
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blockchain-rolebinding
  namespace: blockchain
  labels:
    app.kubernetes.io/name: blockchain
    app.kubernetes.io/part-of: hashfoundry
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
- kind: ServiceAccount
  name: blockchain-serviceaccount
  namespace: blockchain
roleRef:
  kind: Role
  name: blockchain-role
  apiGroup: rbac.authorization.k8s.io
