name: deploy_hashfoundry-react
run-name: deploy_hashfoundry-react

on:
  workflow_call:
    inputs:
      tag:
        description: 'The version tag of the hashfoundry-react image that should be deployed.'
        required: true
        type: string
      env:
        description: 'The target environment. [dev|staging|prod]'
        required: false
        default: dev
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'The version tag of the hashfoundry-react image that should be deployed.'
        required: true
        type: string
      env:
        description: 'The target environment. [dev|staging|prod]'
        required: false
        default: dev
        type: string

jobs:
  deploy-hashfoundry-react:
    name: deploy-hashfoundry-react
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@main
        with:
          ref: main

      - name: Update hashfoundry-react image tag
        run: |
          FILE_NAME=k8s/apps/hashfoundry-react/values.${{ inputs.env }}.yaml
          NEW_TAG=${{ inputs.tag }}
          export FILE_CONTENT=$(cat ${FILE_NAME})
          export CURRENT_TAG=$(echo "${FILE_CONTENT}" | grep 'tag: ' | sed -n -e '/tag:/ s/.*: *//p' | tr -d '"')
          echo "CURRENT_TAG: ${CURRENT_TAG}"
          echo "NEW_TAG: ${NEW_TAG}"
          sed -i "s/${CURRENT_TAG}/${NEW_TAG}/g" ${FILE_NAME}

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "ci(hashfoundry-react): deploy image ${{ inputs.tag }} in ${{ inputs.env }}"

      - name: Generate Git Tag
        id: push-deployment-tag
        run: |
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/hashfoundry/infra.git
          git fetch && git checkout main
          git config user.name "GitHub Actions"
          git config user.email "github-actions@hashfoundry.com"
          git tag --force hashfoundry-react-${{ inputs.env }}
          git push --force origin hashfoundry-react-${{ inputs.env }}
          echo "### Branch TAG Completed :triangular_flag_on_post:	" >> $GITHUB_STEP_SUMMARY
          echo "- hashfoundry-react-${{ inputs.env }}" >> $GITHUB_STEP_SUMMARY
