name: Deploy Argo CD

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'k8s/addons/argo-cd/**'
      - 'k8s/addons/argo-cd-apps/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy-argocd:
    name: Deploy Argo CD to ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'prod') || 'dev' }}
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/staging' && 'staging') || 'dev' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          if [ "$ENVIRONMENT" == "prod" ]; then
            aws eks update-kubeconfig --name hashfoundry-prod --region us-east-1
          elif [ "$ENVIRONMENT" == "staging" ]; then
            aws eks update-kubeconfig --name hashfoundry-staging --region us-east-1
          else
            aws eks update-kubeconfig --name hashfoundry-dev --region us-east-1
          fi

      - name: Deploy Argo CD
        run: |
          cd k8s/addons/argo-cd
          helm dependency update
          helm upgrade --install --create-namespace -n argocd argocd . -f values.yaml -f values.$ENVIRONMENT.yaml

      - name: Deploy Argo CD Apps
        run: |
          cd k8s/addons/argo-cd-apps
          helm upgrade --install --create-namespace -n argocd argo-cd-apps . -f values.yaml -f values.$ENVIRONMENT.yaml
